name: ci - alpine-release

on:
  workflow_call:
    inputs:
      distinct_id:
        description: "Distinct ID for the artifacts"
        required: true
        type: string
      release_tag:
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-24.04-arm

    name: "Publish release qbt-hosts-deps"

    env:
      qbt_build_dir: "qbt-build"

    steps:
      - name: Checkout ${{ inputs.distinct_id }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Host - Download artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          path: "release"
          merge-multiple: true

      - name: Host- Create release - tag - assets
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          artifacts: "release/*.tar.xz"
          replacesArtifacts: true
          tag: "${{ inputs.release_tag }}"
          name: "${{ inputs.release_tag }}"
          allowUpdates: true
          token: "${{ github.token }}"
