name: ci - alpine-release

on:
  workflow_call:
    inputs:
      distinct_id:
        description: "Distinct ID for the artifacts"
        required: true
        type: string
      release_tag:
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-24.04-arm

    name: "Publish release qbt-hosts-deps"

    env:
      qbt_build_dir: "qbt-build"

    steps:
      - name: Checkout ${{ inputs.distinct_id }}
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Host - Download artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          path: "release"
          merge-multiple: true

      - name: Host- Create release - tag - assets
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          artifacts: "release/*.tar.xz"
          replacesArtifacts: true
          tag: "${{ inputs.release_tag }}"
          name: "${{ inputs.release_tag }}"
          allowUpdates: true
          token: "${{ github.token }}"
