# @credits https://github.com/c0re100/qBittorrent-Enhanced-Edition
name: ci - alpine build

on:
  workflow_call:
    inputs:
      distinct_id:
        description: "Distinct id"
        required: false
        type: string
      workflow-files:
        description: "Alpine: workflow-files files"
        required: true
        type: string
      debug:
        description: "debug builds"
        required: true
        type: string
      script_name:
        description: "script name"
        required: true
        type: string
    outputs:
      release_tag:
        value: ${{ jobs.build-alpine.outputs.release_tag }}

jobs:
  build-alpine:
    outputs:
      release_tag: ${{ steps.build_outputs.outputs.release_tag }}
    runs-on: "${{ matrix.runs_on }}"
    strategy:
      fail-fast: false
      matrix:
        os_id: ["alpine"]
        os_version_id: ["edge"]
        native_or_cross:
          ["x86_64-native", "x86_64-cross", "aarch64-native", "aarch64-cross"]
        set_skip_icu: ["yes", "no"]
        qbt_libtorrent_version: ["", "1.2", "2.0"]
        include:
          - native_or_cross: "x86_64-native"
            qbt_cross_name: ""
            runs_on: "ubuntu-24.04"

          - native_or_cross: "x86_64-cross"
            qbt_cross_name: ""
            runs_on: "ubuntu-24.04-arm"

          - native_or_cross: "aarch64-native"
            qbt_cross_name: "x86_64"
            runs_on: "ubuntu-24.04-arm"

          - native_or_cross: "aarch64-cross"
            qbt_cross_name: "aarch64"
            runs_on: "ubuntu-24.04-arm"

          - set_skip_icu: "yes"
            suffix: "iconv"

          - set_skip_icu: "no"
            suffix: "icu"

          - qbt_libtorrent_version: ""
            libtorrent_info: ""

          - qbt_libtorrent_version: "1.2"
            libtorrent_info: "-lt12"

          - qbt_libtorrent_version: "2.0"
            libtorrent_info: "-lt20"

    name: "${{ matrix.native_or_cross }}-qt6-${{ matrix.suffix }}${{ matrix.libtorrent_info }}"

    env:
      qbt_build_dir: "qbt-build"
      script_name: ${{ inputs.script_name }}
      container_name: "multiarch"
      name: "${{ matrix.native_or_cross }}-qt6-${{ matrix.suffix }}${{ matrix.libtorrent_info }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Host - Create Docker template env file
        env:
          set_workflow_files: ${{ inputs.workflow-files }}
          set_build_debug: ${{ inputs.debug }}
        run: |
          printf '%s\n' "qbt_build_dir=${{ env.qbt_build_dir }}" > env.custom
          printf '%s\n' "qbt_qt_version=${{ matrix.qbt_qt_version }}" >> env.custom
          printf '%s\n' "qbt_cross_name=${{ matrix.qbt_cross_name }}" >> env.custom
          printf '%s\n' "qbt_patches_url=${{ github.repository }}" >> env.custom
          printf '%s\n' "qbt_skip_icu=${{ matrix.set_skip_icu }}" >> env.custom
          printf '%s\n' "qbt_libtorrent_version=${{ matrix.qbt_libtorrent_version }}" >> env.custom
          printf '%s\n' "qbt_qt_tag=${{ matrix.qbt_qt_tag }}" >> env.custom
          printf '%s\n' "qbt_workflow_files=${set_workflow_files}" >> env.custom
          printf '%s\n' "qbt_build_debug=${set_build_debug}" >> env.custom
          printf '%s\n' "qbt_revision_url=${{ github.repository }}" >> env.custom

      # - name: Host - Github env to container
      #   run: env >> env.custom

      - name: Host - check stuff
        run: export $(cat env.custom) && bash ${script_name}

      - name: Host - qBittorrent v5 transition
        run: |
          if [[ -f "${qbt_build_dir}/release_info/disable-qt5" || -f "disable-qt5" ]]; then
              printf '%s\n' "disable_qt5=yes" >> $GITHUB_ENV
              printf '%s\n' "Found file: \`disable-qt5\` -> setting env: \`disable_qt5=yes\`" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Host - phased updates
        run: printf '%s\n' 'APT::Get::Always-Include-Phased-Updates "false";' | sudo tee /etc/apt/apt.conf.d/99-phased-updates

      - name: Host - update
        run: sudo apt-get update

      # - name: Host - upgrade
      #   run: sudo apt-get -y upgrade

      - name: Host - set up qemu-user-static binfmt-support

        run: sudo apt install libpipeline1 qemu-user-static binfmt-support

      - name: Host - Create docker ${{ env.multiarch }} container

        run: |
          # We create an Alpine edge container for cross-compilation with a user named gh which has same id as runner 1001 and provide sudo access
          # This way we can run commands as a non-root user, avoiding permission issues on host runner. Switching between user and root as needed.
          docker run --name ${container_name} -it -d --env-file env.custom -w /home/gh -v ${{ github.workspace }}:/home/gh ${{ matrix.os_id }}:${{ matrix.os_version_id }}
          # Create the user gh with the id 1001:1001 which is the same as the runner user id and group id.
          docker exec ${container_name} sh -c 'adduser -h /home/gh -Ds /bin/bash -u 1001 gh && apk add sudo'
          # Allow the user gh to run sudo without password prompt: docker exec -u gh:gh ${container_name} sudo ls
          docker exec ${container_name} sh -c 'printf "%s" "gh ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/gh'

      - name: Host - patches
        run: |
          mkdir -p ${qbt_build_dir}/patches
          [[ -d ${qbt_build_dir}/patches ]] && cp -rf patches/* ${qbt_build_dir}/patches/ || true

      - name: Docker - apk update
        run: docker exec ${container_name} apk update

      - name: Docker - apk install bash
        run: docker exec ${container_name} apk add bash

      - name: Docker - Bootstrap test tools
        run: docker exec ${container_name} bash ${script_name} update install_test

      - name: Docker - Bootstrap core deps
        run: docker exec ${container_name} bash ${script_name} install_core

      - name: Docker - Bootstrap build
        run: docker exec -u gh:gh ${container_name} bash ${script_name} -bs-a

      - name: Docker - zlib-ng
        run: docker exec -u gh:gh ${container_name} bash ${script_name} zlib

      - name: Docker - iconv
        run: docker exec -u gh:gh ${container_name} bash ${script_name} iconv

      - name: Docker - icu
        run: docker exec -u gh:gh ${container_name} bash ${script_name} icu

      - name: Docker - openssl
        run: docker exec -u gh:gh ${container_name} bash ${script_name} openssl

      - name: Docker - boost
        if: matrix.qbt_libtorrent_version
        run: docker exec -u gh:gh ${container_name} bash ${script_name} boost

      - name: Docker - libtorrent
        if: matrix.qbt_libtorrent_version
        run: docker exec -u gh:gh ${container_name} bash ${script_name} libtorrent

      - name: Docker - double_conversion
        run: docker exec -u gh:gh ${container_name} bash ${script_name} double_conversion

      - name: Docker - qtbase
        run: docker exec -u gh:gh ${container_name} bash ${script_name} qtbase

      - name: Docker - qttools
        run: docker exec -u gh:gh ${container_name} bash ${script_name} qttools

      - name: qt6 release tag
        run: |
          qt6_release_tag=$(jq -r '.qt6' ${{ env.qbt_build_dir }}/release_info/qt6-dependency-version.json)
          printf '%s\n' "release_tag=v${qt6_release_tag}"
          printf '%s\n' "release_tag=v${qt6_release_tag}" >> $GITHUB_ENV

      - name: clean ${{ env.qbt_build_dir }}
        run: |
          # mcm stuff
          rm -rf ${qbt_build_dir}/bin/ninja
          rm -rf ${qbt_build_dir}/bin/x86_64-linux-musl-*
          rm -rf ${qbt_build_dir}/lib/gcc
          rm -rf ${qbt_build_dir}/lib/bfd-plugins
          rm -rf ${qbt_build_dir}/libexec/gcc
          rm -rf ${qbt_build_dir}/share/gcc-*
          rm -rf ${qbt_build_dir}/share/man
          rm -rf ${qbt_build_dir}/x86_64-linux-musl
          rm -rf ${qbt_build_dir}/x86_64-linux-musl.tar.gz

          # qbt stuff
          rm -rf ${qbt_build_dir}/completed
          rm -rf ${qbt_build_dir}/graphs
          rm -rf ${qbt_build_dir}/patches
          rm -rf ${qbt_build_dir}/release_info
          rm -rf ${qbt_build_dir}/logs
          rm -rf ${qbt_build_dir}/.active-toolchain-info

      - name: archive ${{ env.qbt_build_dir }}
        run: tar cJf "${name}.tar.xz" "${qbt_build_dir}"

      - name: Generate artifact attestation  ${{ inputs.distinct_id }}
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: "${{ env.name }}.tar.xz"

      - name: Host - Upload ${{ env.name }}
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.name }}"
          path: "${{ env.name }}.tar.xz"

      - name: Set outputs
        id: build_outputs
        run: printf '%s\n' "release_tag=${release_tag}" >> $GITHUB_OUTPUT
